from os import environ as env

class Telegram:
    API_ID = int(env.get("TELEGRAM_API_ID", 22081293))  # The API ID for the Telegram Bot
    API_HASH = env.get("TELEGRAM_API_HASH", "6c800426d11c5fb6ede182290e1808be")  # The API hash for the Telegram Bot
    OWNER_ID = int(env.get("OWNER_ID", 1454539771))  # The ID of the bot owner
    ALLOWED_USER_IDS = env.get("ALLOWED_USER_IDS", "").split()  # List of allowed user IDs for the bot
    BOT_USERNAME = env.get("TELEGRAM_BOT_USERNAME", "FiletolinkCimaMixbot")  # The Telegram bot's username
    BOT_TOKEN = env.get("TELEGRAM_BOT_TOKEN", "7835727299:AAGXswl_arwU8Igzierhpp67USAwHIlZVsU")  # The bot token
    CHANNEL_ID = int(env.get("TELEGRAM_CHANNEL_ID", -2482473456))  # The Telegram channel ID
    SECRET_CODE_LENGTH = int(env.get("SECRET_CODE_LENGTH", 24))  # The length of the secret code generated by the bot

class Server:
    BASE_URL = env.get("BASE_URL", "http://127.0.0.1:8080")  # The base URL for the server
    BIND_ADDRESS = env.get("BIND_ADDRESS", "0.0.0.0")  # The address the server binds to
    PORT = int(env.get("PORT", 8080))  # The port the server listens on

# LOGGING CONFIGURATION
LOGGER_CONFIG_JSON = {
    'version': 1,
    'formatters': {
        'default': {
            'format': '[%(asctime)s][%(name)s][%(levelname)s] -> %(message)s',
            'datefmt': '%d/%m/%Y %H:%M:%S'
        },
    },
    'handlers': {
        'file_handler': {
            'class': 'logging.FileHandler',
            'filename': 'event-log.txt',  # The file where logs will be stored
            'formatter': 'default'
        },
        'stream_handler': {
            'class': 'logging.StreamHandler',
            'formatter': 'default'
        }
    },
    'loggers': {
        'uvicorn': {
            'level': 'INFO',  # Log level for uvicorn
            'handlers': ['file_handler', 'stream_handler']
        },
        'uvicorn.error': {
            'level': 'WARNING',  # Log level for uvicorn errors
            'handlers': ['file_handler', 'stream_handler']
        },
        'bot': {
            'level': 'INFO',  # Log level for bot activities
            'handlers': ['file_handler', 'stream_handler']
        },
        'hydrogram': {
            'level': 'INFO',  # Log level for hydrogram activities
            'handlers': ['file_handler', 'stream_handler']
        }
    }
}
